import { TopBar } from "@/components/layout/top-bar";
import "./globals.css";
import LeftSidebar from "@/components/layout/left-sidebar";

export const metadata = {
  title: "Dashboard - AOI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
