import "./globals.css";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
  title: "Dashboard - AOI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Analytics />
      <body>{children}</body>
    </html>
  );
}
